### ISSUE TITLE
[Suggestion] Automatically register blueprint blocks as flammable/compostable

### ISSUE THREAD

**Issue by Ketok4321** [team-abnormals/blueprint#134]
For example when new LogBlock is created it would automatically register itself as flammable, or when new BlueprintLeavesBlock is created it would register itself as compostable.
It could be very easily achieved by just calling `DataUtil.registerFlammable`/`DataUtil.registerCompostable` within constructors

**Comment by SmellyModder** [comment]
While this could simplify and ease the creation of logs for some people, it could also be a nuisance to modders that don't want their logs to be flammable, compostable, and/or want abnormal values for their logs flammable and compostable values.
Also, registering flammable and compostables during block construction is unsafe because order issues can occur.

Some modders may also like having all their flammable and compostable values organized and easily viewable in their codebase.
