### ISSUE TITLE
[1.18.1] Exception generating new chunk. (Blueprint + TerraBlender issue?).

### ISSUE THREAD

**Issue by Gbergz** [team-abnormals/blueprint#144]
Title^

Running around generating the nether caused a crash, happened multiple times.

Minecraft: 1.18.1
Forge: 39.0.75
TerraBlender: 1.1.0.73 | https://www.curseforge.com/minecraft/mc-mods/terrablender/files/3619749
Blueprint: 5.1.1 | https://www.curseforge.com/minecraft/mc-mods/blueprint/files/3645224

**Crash-Report**: https://gist.github.com/Gbergz/647eb18f2b75db17eb1aa1ae857d655b

**Comment by SmellyModder** [comment]
This crash is very similar to a TerraBlender issue that's been open for a while: https://github.com/Glitchfiend/TerraBlender/issues/27
Have you tried removing Blueprint and seeing if the crash no longer occurs?
Blueprint might only be in the crash report stack trace because Blueprint has a modded biome system.

**Comment by SmellyModder** [comment]
I did some testing, and this appears to be a Terrablender issue.
