### ISSUE TITLE
Server Crashing, report references Blueprint

### ISSUE THREAD

**Issue by Flugel3** [team-abnormals/blueprint#145]
It seems very unusual that a Library would cause an issue like this but forgive me I don't really know anything about these kinds of things.
[crash-2022-02-23_00.57.59-server.txt](https://github.com/team-abnormals/blueprint/files/8127283/crash-2022-02-23_00.57.59-server.txt)

The issue seems to occur only whenever certain things with GUIs are interacted with, like chests or even villagers seem to be able to crash it. I'm not sure of a surefire way to replicate this because the factors seem very numerous and this only occurs on servers. More specifically it started happening when I switched from hosting the server myself to Bisect Hosting. I'm sorry if this report doesn't actually apply to blueprint or if I'm wasting your time, I know little to nothing about these sorts of things.

**Comment by SmellyModder** [comment]
I'm not sure what caused the crash here, but the logs suggest that somehow a large amount of `ModdedBiomeSource` instances were getting wrapping by each other. The only way that could happen is if the `ServerAboutToStartEvent` got fired many, many times for the same server instance, but that should never happen.
If this issue is still occurring on the latest version of Blueprint 1.18.2, I'll reopen this issue.
