### ISSUE TITLE
Banner pattern crash (mod incompat probably)

### ISSUE THREAD

**Issue by thelegitdolt** [team-abnormals/blueprint#162]
https://gist.github.com/thelegitdolt/05ed593ec78badb9630748dda64f068d i just got a crash from putting a banner pattern inside a loom, vanilla patterns seem to be fine

**Comment by thelegitdolt** [comment]
i will see if i can get the crash to stop by removing mods by myself later, currenlty am in school

**Comment by SmellyModder** [comment]
It looks like the `BannerRenderer` can't get the `Material` for the corresponding `BannerPattern`. (See line 111 in `BannerRenderer`)
The `BannerRenderer` looks up the `Material` in a map, but since no `Material` exists for the `BannerPattern`, it gets a null `Material`, which causes the crash.
Register your banner patterns appropriately before the `Sheets` class gets loaded.
I'm pretty sure this is not a Blueprint issue, but I will reopen this issue if it is.

**Comment by thelegitdolt** [comment]
i've also ran into this using the neapolitan one, so i don't think it's a problem with registry

**Comment by thelegitdolt** [comment]
it's probably a mod incompat i'll do testing

**Comment by SmellyModder** [comment]
> it's probably a mod incompat i'll do testing

Could be.
I don't think it's a Blueprint issue because Blueprint's `BannerManager` uses the `BannerPattern#create()` method provided by Forge.

**Comment by thelegitdolt** [comment]
it's with pollen

**Comment by SmellyModder** [comment]
Probably should report it to Pollen then.
As I said before, Blueprint's `BannerManager` uses the `BannerPattern#create()` method provided by Forge, meaning this issue would be an incompatibility at the individual mod level.

Neopolitan registers its banner patterns in the constructor of the `Neapolitan` class by classloading `NeapolitanPaintingTypes`.
This makes me think that Pollen is loading the `Sheets` class early.

**Comment by thelegitdolt** [comment]
actually i did a little more testing and it seems to be an enhanced mushrooms problem. I'll report it to them. Thanks for hearing me
