### ISSUE TITLE
Blueprint and Abnormals mods conflict with Terrablender and BOP biomes on servers 1.19+

### ISSUE THREAD

**Issue by SmallSansSerif** [team-abnormals/blueprint#166]
I'm using the 1.19 version of Blueprint and can't get BOP biomes to appear in a server. https://www.curseforge.com/minecraft/mc-mods/blueprint/files/3898272

Biomes do appear in single player with Blueprint. Remove Blueprint and the Abnormals mods on the server and the BOP biomes appear. So, there must be some kind of conflict with Blueprint, Terrablender and BOP.

**Comment by CorgiTaco** [comment]
Most likely related to this: https://github.com/team-abnormals/blueprint/blob/1.19.x/src/main/java/com/teamabnormals/blueprint/common/world/modification/ModdedBiomeSlicesManager.java#L108-L116

To probably fix it...

This: https://github.com/team-abnormals/blueprint/blob/1.19.x/src/main/java/com/teamabnormals/blueprint/common/world/modification/ModdedBiomeSource.java#L33

Should probably extend `MultiNoiseBiomeSource`

I'd suggest for a much better/easier compatibility with other biome mods like BYG & BOP, & Quark iirc(for their cave biome) to use  [Terrablender](https://www.curseforge.com/minecraft/mc-mods/terrablender)

**Comment by SmellyModder** [comment]
Seems the issue was happening because Blueprint and Terrablender were both on lowest priority for their `ServerAboutToStartEvent` listeners causing Blueprint to sometimes run its listener before Terrablender's.
When Blueprint would run first, it messed up Terrablender because `ModdedBiomeSource` isn't an instance of `MultiNoiseBiomeSource`.

We know that Terrablender exists, and we were more comfortable creating our own more versatile system compatible with Terrablender. I never noticed this issue because Blueprint's listener always ran last.

**Comment by Atlantispy** [comment]
Hi @SmellyModder, Can this fix be backported to 1.18 please?
