### ISSUE TITLE
Incompatibility with Pollen causes Advancement Modifiers to stop working

### ISSUE THREAD

**Issue by LaGz4643** [team-abnormals/blueprint#188]
No other mods are installed other than Pollen, Blueprint, and other Team Abnormals mods.

The issue is very strange and only happens with some combinations of mods. For example, the following list of mods work correctly:
Upgrade Aquatic, Woodworks, Savage & Ravage, Personality, Neapolitan, Incubation, Buzzier Bees, Boatload, Atmospheric.

Adding Berry Good to this list breaks every mod's advancement modifiers, but if you have only Berry Good and one other Team Abnormals mod installed, they work correctly.

I'm not sure if this is something that has to be fixed on Pollen or Blueprint's side.

**Comment by SmellyModder** [comment]
This is a bizarre issue; send your logs.
Also, does this issue not happen with just Blueprint and Berry Good but then happens when only Pollen gets added?

**Comment by LaGz4643** [comment]
I tested this further and tried the following steps:

1. Started with Blueprint + Berry Good and modifiers work correctly.
2. Added Pollen and modifiers still work.
3. Added Atmospheric, Autumnity, Buzzier Bees, Savage & Ravage, and all modifiers still work.
4. Added Upgrade Aquatic, still works.
5. Added Incubation, still works.
6. Added Neapolitan, still works.
7. Added Boatload, still works.
8. Added Woodworks, all advancement modifiers stop working.
9. Removed Pollen, all modifiers now work.

It seems like Pollen only breaks the modifiers if enough mods are loaded and not specifically because of Berry Good being added. I'm not sure which logs I should send as I relaunched the game many times. Should I send all of the logs from the testing above in order or only specific ones?

**Comment by SmellyModder** [comment]
Have you tested to see if it's an incompatibility between Woodworks and Pollen?
Sure, send all the logs.

**Comment by LaGz4643** [comment]
I tested with Pollen, Blueprint, Woodworks, and also Atmospheric so I could see if advancement modifiers still work as Woodworks doesn't seem to have any modifiers. The advancement modifiers all work correctly.

Log Files:

Blueprint, Berry Good, Pollen, Atmospheric, Autumnity, Buzzier Bees, and Savage & Ravage:
The logs for the first 3 steps listed above are not in my logs folder. I've looked through every log file and I used a new minecraft instance during this testing to keep them separate and they are missing somehow.

Added Upgrade Aquatic:
[2023-02-03-1.log](https://github.com/team-abnormals/blueprint/files/10607836/2023-02-03-1.log)

Added Incubation:
[2023-02-03-2.log](https://github.com/team-abnormals/blueprint/files/10607837/2023-02-03-2.log)

Added Neapolitan:
[2023-02-03-3.log](https://github.com/team-abnormals/blueprint/files/10607838/2023-02-03-3.log)

Added Boatload:
[2023-02-03-4.log](https://github.com/team-abnormals/blueprint/files/10607839/2023-02-03-4.log)

Added Woodworks and modifiers stop working:
[2023-02-03-5.log](https://github.com/team-abnormals/blueprint/files/10607840/2023-02-03-5.log)

Removed Pollen and everything works correctly:
[2023-02-03-6.log](https://github.com/team-abnormals/blueprint/files/10607841/2023-02-03-6.log)

**Comment by SmellyModder** [comment]
It looks like Blueprint's advancement modifiers are getting loaded, but they're not getting processed when advancements are getting loaded. This mean's something weird must be happening in Blueprint's [`AdvancementBuilderMixin`](https://github.com/team-abnormals/blueprint/blob/6bc90f9ebbe1e00e8934637a5ee75b6579330147/src/main/java/com/teamabnormals/blueprint/core/mixin/AdvancementBuilderMixin.java).

I just looked at Pollen's code, and I think this is an issue on their side.
In Pollen's [`AdvancementBuilderMixin`](https://github.com/MoonflowerTeam/pollen/blob/1.18.x/forge/src/main/java/gg/moonflower/pollen/core/mixin/forge/data/AdvancementBuilderMixin.java), they are reconstructing the `Advancement.Builder` instance, which would undo any modifications done by other mixins that run before it.
Perhaps this issue only happens with Woodworks because the order of the mixins can fluctuate?

**Comment by SmellyModder** [comment]
I am closing this issue because a fix is probably never coming and would be irrelevant anyway.
From what I've heard, Pollen is discontinued, or at the very least, is discontinuing their advancement modifiers.
Additionally, Pollen is not on 1.20.1+, and we are only maintaining our mods on 1.20.1+ right now.
