### ISSUE TITLE
Redistribution

### ISSUE THREAD

**Issue by aaronliu0130** [team-abnormals/blueprint#192]
The license denies redistribution, but I thought maybe an exception can be made for modrinth, so here goes:
Do modpack authors have the right to redistribute this mod as an override jar, i.e. in Modrinth modpacks? Alternatively, would you like to release on Modrinth or GitHub?

Additional context: Curseforge does not allow downloading mods from curseforge for modrinth modpacks. So when your mod is not available for download elsewhere, the only option is to redistribute the mod's `.jar` file inside the modpack and move the files to the `mods` directory as an override.

**Comment by SmellyModder** [comment]
Unfortunately, an exception will not be made for Modrinth. We also have yet to make plans of putting our mods on Modrinth.
I'm sorry for the inconvenience. If you want to use our mods in a Modrinth mod pack, you must tell users to download our mods manually separately.
I don't control whether our mods will go on Modrinth, so the best you can do is hope for now. We can't make an exception like this for various reasons, but I won't explain to avoid drama...

_Also, don't open issues like this in the future because this isn't a bug. This would be more fitting if sent over Discord. Plus, it would get more attention there._
