### ISSUE TITLE
Crash when entering the Nether

### ISSUE THREAD

**Issue by MaxWasUnavailable** [team-abnormals/blueprint#194]
Possible conflict with Biomes O Plenty?

The entire server crashed when a user entered the Nether. The crash reports seem to indicate it's a method of Blueprint that raises an exception, or is at least involved.

*Versions:*
- Blueprint: 1.18.2-5.5.0.jar
- Forge: 40.2.1

*Crash Reports:*

[crash-2023-04-11_02.02.54-server.txt](https://github.com/team-abnormals/blueprint/files/11195595/crash-2023-04-11_02.02.54-server.txt)
[crash-2023-04-10_23.32.08-server.txt](https://github.com/team-abnormals/blueprint/files/11195596/crash-2023-04-10_23.32.08-server.txt)

**Comment by SmellyModder** [comment]
Even though a Blueprint class is mentioned in the stack trace, this is not a Blueprint issue.
The feature order cycle is a vanilla error. Due to the internals of Blueprint's modded biome system, Blueprint gets mentioned.
Use the [Cyanide mod](https://www.curseforge.com/minecraft/mc-mods/cyanide-forge) to get a better analysis of the error.

**Comment by MaxWasUnavailable** [comment]
For future reference, if anyone stumbles upon this issue:

The Rare Ice mod ended up being responsible for this.
