### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Anewri** [team-abnormals/blueprint#196]
https://bytebin.lucko.me/0oAlOBrXOj

**Comment by SmellyModder** [comment]
Even though a Blueprint class is mentioned in the stack trace, this is not a Blueprint issue.
The feature order cycle is a vanilla error. Due to the internals of Blueprint's modded biome system, Blueprint gets mentioned.
Use the [Cyanide mod](https://www.curseforge.com/minecraft/mc-mods/cyanide-forge) to get a better analysis of the error.
