### ISSUE TITLE
[1.19.2] crash when generating a world

### ISSUE THREAD

**Issue by Kuggle01** [team-abnormals/blueprint#197]
https://mclo.gs/MuwF9hk The game crashes whenever I try to generate a new world, before it even gets past 0% on the generation screen. According too Not enough crashes, the culprit is Blueprint, I'd really like too keep this and the rest of the team abnormals mods in my pack, so any help would be greatly appreciated

**Comment by grimmtastic** [comment]
I'm having this issue too. I really enjoy the TeamAbnormals mods and want to keep them too
https://mclo.gs/ow5jFJJ

**Comment by grimmtastic** [comment]
Nevermind I found the issue, I saw we both had wizardy delight and so I removed it. That mod is causing the issue @Kuggle01

**Comment by SmellyModder** [comment]
Yeah, this is a classic feature order cycle crash.
Even though a Blueprint class is mentioned in the stack trace, this is not a Blueprint issue.
_Feature order cycle_ is a vanilla error. Due to the internals of Blueprint's modded biome system, Blueprint gets mentioned.
Use the [Cyanide mod](https://www.curseforge.com/minecraft/mc-mods/cyanide-forge) to get a better analysis of the error.
