### ISSUE TITLE
lag server

### ISSUE THREAD

**Issue by kitovoi111** [team-abnormals/blueprint#227]
https://github.com/AlexModGuy/AlexsCaves/issues/972

**Comment by SmellyModder** [comment]
I am closing this because it doesn't look like Blueprint is the primary cause of the lag.

Notice that `MultiNoiseBiomeSource.getNoiseBiome()` is the largest percentage of the 30.88% total, and that method is vanilla.
The Blueprint `BiomeUtil` related methods are not vanilla methods, but internally, they use vanilla methods.
![image](https://github.com/team-abnormals/blueprint/assets/41268323/c449852e-f4ea-494d-9822-bd5a30016cba)

The only method that does not primarily use vanilla methods is `ModdedBiomeSource.getSlice()`, which takes up only a tiny percentage.

This makes me believe that after removing Blueprint, there would still be lag because vanilla methods are being used too much.
Minecraft is generally slow at calculating the noise biome at a position, so optimization must be taken seriously. In vanilla, this problem can be seen when you try to locate a rare biome using the `/locate` command, as the game freezes for a few seconds.
