### ISSUE TITLE
Incompatibility with Continuity mod

### ISSUE THREAD

**Issue by Axi0L** [team-abnormals/blueprint#240]
Connected textures with Continuity mod on Forge using Sinytra Connector and Lazurite don't work while Blueprint is installed.
![2024-05-06_00 50 28](https://github.com/team-abnormals/blueprint/assets/166019493/805e63fc-41d7-4137-8d2b-c7e66c76cdbd)
![2024-05-06_00 51 11](https://github.com/team-abnormals/blueprint/assets/166019493/db4258e1-866f-47ca-b755-8f08fbe79fa7)

First image without Blueprint mod, second image with it installed.

**Comment by SmellyModder** [comment]
Blueprint is not designed to support Fabric, so any issues you get with it on Fabric are not our responsibility.
Also, I have no idea what could be causing this issue because I am unfamiliar with the codebases of Continuity and Connector.
It would be better to open this issue on Connector because they can more likely explain the cause.
